### ISSUE TITLE
[Bug] Itsi Scheduler fails to build on Ruby 4.0.0

### ISSUE THREAD

**Issue by p8** [wouterken/itsi#23]
### Ruby version

4.0.0

### Itsi version(s)

itsi 0.2.20

### Minimal `Itsi.rb` configuration

The config isn't relevant as the gem fails to build.

### Steps to Reproduce

Checkout the repo:

```bash
git checkout https://github.com/p8/FrameworkBenchmarks
git fetch origin
git switch -c rack/rack/itsi-ruby-4.0 origin/rack/itsi-ruby-4.0
```

Run the rack test with:

```bash
./tfb --test rack-itsi --mode verify
```

### What did you expect to happen? What happened instead?

No error 

### Relevant logs, stack traces, or error output

```log
Compiling itsi_instrument_entry v0.1.0
(/usr/local/bundle/gems/itsi-scheduler-0.2.20/ext/itsi_instrument_entry)
   Compiling rcgen v0.13.2
error[E0308]: mismatched types
-->
/usr/local/bundle/gems/itsi-scheduler-0.2.20/ext/itsi_scheduler/.rb-sys/stable/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/magnus-0.7.1/src/fiber.rs:469:21
    |
466 |                 Value::new(rb_fiber_raise(
|                            -------------- arguments to this function are
incorrect
...
469 |                     &e.as_rb_value() as *const VALUE,
|                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ types differ in
mutability
    |
    = note: expected raw pointer `*mut u64`
               found raw pointer `*const u64`
note: function defined here
-->
/usr/local/bundle/gems/itsi-scheduler-0.2.20/ext/itsi_scheduler/target/release/build/rb-sys-f61b8fb249a42022/out/bindings-0.9.111-mri-aarch64-linux-4.0.0.rs:1:588357
    |
1 | ...xidize-rb/rb-sys) for Ruby mri-aarch64-linux-4.0.0"] pub fn
rb_fiber_raise (fiber : VALUE , argc : :: std :: os :: raw :: c_int , argv...
|
^^^^^^^^^^^^^^
error[E0609]: no field `typed_flag` on type `&rb_sys::RTypedData`
-->
/usr/local/bundle/gems/itsi-scheduler-0.2.20/ext/itsi_scheduler/.rb-sys/stable/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/magnus-0.7.1/src/r_typed_data.rs:202:58
    |
202 |                     let typed_flag = typed_data.as_ref().typed_flag;
|                                                          ^^^^^^^^^^
unknown field
    |
    = note: available fields are: `basic`, `fields_obj`, `type_`, `data`
Some errors have detailed explanations: E0308, E0609.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `magnus` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:580: target/release/libitsi_scheduler.so] Error 101
make failed, exit code 2
Gem files will remain installed in /usr/local/bundle/gems/itsi-scheduler-0.2.20
for inspection.
```

### Final checklist

- [x] I have tested the minimal reproduction case and confirmed it fails
- [x] I am using the latest released versions of Itsi and its supporting gems
- [x] I have reviewed the documentation and existing issues for this problem
